name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: pull docker image
      run: sudo docker pull naveedalirehmani/actions
    - name: delete old docker container
      run: sudo docker rm -f actions-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8080 --name actions-container naveedalirehmani/actions