name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASS}}
      run: docker -u $DOCKER_USERNAME -p $DOCKER_PASS

    - name: Build the Docker image
      run: docker build -t actions .

    - name: Push to Docker Hub
      run: docker push naveedalirehmani/actions


      